---
title: "Clean Phytoplankton Data"
author: "Jeanette Clark"
date: '2022-05-05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(readxl)
library(readr)
library(janitor)
library(summarytools)
library(dplyr)
library(knitr)
library(stringr)

st_options(use.x11 = FALSE)
```

Read in phytoplankton data 
```{r}
phy <- read_excel("data_raw/phyto_data_raw.xlsx", guess_max = 12359, sheet = 2, na = c("", "n/a", "NA")) %>% 
    clean_names() %>% 
    mutate(organisims_per_ml = factor * unit_abundance) %>% 
    mutate(sample_time = as.character(sample_time)) %>% 
    mutate(sample_time = str_extract(sample_time, "[0-9]{2}:[0-9]{2}:[0-9]{2}$")) %>% 
    mutate(colony_filament_individual_group_code = tolower(colony_filament_individual_group_code)) %>% 
    mutate(colony_filament_individual_group_code = ifelse(colony_filament_individual_group_code == "7.4", NA, colony_filament_individual_group_code)) %>% 
    mutate(colony_filament_individual_group_code = ifelse(colony_filament_individual_group_code == "c3", "c", colony_filament_individual_group_code)) %>% 
    mutate(station_code_original = station_code) %>% 
    mutate(station_code = str_extract(station_code_original, "^[A-Z0-9]+")) %>% 
    mutate(sample_time = ifelse(is.na(sample_time), "00:00:00", sample_time)) %>% 
    mutate(datetime = paste(as.character(sample_date), sample_time)) %>% 
    mutate(datetime = as.POSIXct(datetime, tz = "UTC"))

```

Read in wq data 
```{r}
wq <- read_csv("data_clean/clean_WQ_phys_20220210.csv", show_col_types = F) %>% 
    clean_names() %>% 
    mutate(datetime = as.POSIXct(datetime, tz = "")) %>% 
    mutate(sample_date = as.Date(datetime)) 
```


```{r, results = "asis"}
st_options(bootstrap.css = FALSE, 
           dfSummary.silent = TRUE)
st_css()

print(dfSummary(phy,
          valid.col = FALSE,  
          plain.ascii = FALSE, 
          graph.magnif = 0.75,
          style = "grid"), method = "render")
```

Check IDs

```{r}
wq_ids <- wq %>% 
    clean_names() %>% 
    mutate(datetime = as.POSIXct(datetime, tz = "")) %>% 
    mutate(sample_date = as.Date(datetime)) %>% 
    mutate(unique_id = paste0(station_code,"_",datetime))%>%
    filter(!is.na(datetime)) %>%
    distinct(sample_date, datetime, station_code, physical_data_id, unique_id) 

phy_ids <- phy %>% 
    filter(station_code %in% c("SHR", "LIS", "STTD")) %>% 
    filter(!is.na(datetime)) %>%
    mutate(unique_id = paste0(station_code, "_", datetime)) %>% 
    distinct(unique_id, station_code, station_code_original, datetime, sample_date)
```

Checking for missing samples on phyto and wq side - still a couple missing
```{r}
phy_wq <- full_join(phy_ids, wq_ids, by = c("station_code", "sample_date", "unique_id")) %>% 
    select(unique_id, physical_data_id, station_code, station_code_original, sample_date, datetime.x, datetime.y) %>% 
    mutate(time_diff = abs(datetime.x - datetime.y)) %>% 
    rename(datetime_phytoplankton = datetime.x,
           datetime_wq = datetime.y) %>% 
    mutate(dupe = duplicated(unique_id)) %>%
    filter(!grepl("DUP", station_code_original))

phy_a <- anti_join(phy_ids, wq_ids, by = c("station_code", "sample_date"))
hist(phy_a$sample_date, breaks = "months")


# write.csv(phy_wq, "phy_loc.csv", row.names = F)
```

Join dataset 
* may consider changing this to left_join later 
* may consider renaming eventID = unique_id
* may consider adding another ID for each row
```{r}
phy_joined <- full_join(phy, wq) %>%
  rename(event_id = unique_id)
```

Reorder the columns for the final dataset

```{r}
id_cols <- c("sample_date",
             "sample_time",
             "datetime",
             "station_code",
             "station_code_original",
             "physical_data_id",
             "event_id",
             "method_code",
             "depth_m")

sample_info_cols <- c("volume_received_m_l",
                      "volume_analyzed_m_l",
                      "organisims_per_ml",
                      "percent_of_sample_counted",
                      "field_of_view_mm2",
                      "slide_chamber_area_mm2",
                      "area_counted",
                      "dimension",
                      "number_of_fields_counted",
                      "factor",
                      "bsa_tin",
                      "bsa_number",
                      "taxonomist",
                      "comments")

measurement_colnames <- c("organisims_per_ml",
                          "unit_abundance",
                          "number_of_cells_per_unit",
                          "taxon",
                          "genus",
                          "species",
                          "synonym",
                          "diatom_soft_body",
                          "colony_filament_individual_group_code",
                          "shape")

colnames_init <- c(id_cols, sample_info_cols, measurement_colnames)
colnames_remain <- colnames(phy_joined)[which(!(colnames(phy_joined) %in% colnames_init))]

phy_final <- phy_joined %>% 
    select(all_of(colnames_init), all_of(colnames_remain))

```




